### ISSUE TITLE
mobile view

### ISSUE THREAD

**Issue by 13Aluminium** [13Aluminium/term#4]
website isntn responsive. In mobile view keyboard isnt working as well as to hit enter user have to hit enter 2 times.

**Comment by ketul-pandya** [comment]
ok i'll try to solve it.

**Comment by krishnanpandya007** [comment]
> ok i'll try to solve it.

please solve then, no fake commits plz🙏🏻

**Comment by ketul-pandya** [comment]
Plzz read it carefully I said I'll try so I'm working on it.

**Comment by 13Aluminium** [comment]
still working??
