### ISSUE TITLE
Add jokes api

### ISSUE THREAD

**Issue by 13Aluminium** [13Aluminium/term#83]
Add API of knock knock to the "knock " function mentioned in version 2 in javascript.js file

**Comment by 13Aluminium** [comment]
the knock function is at line 262 please take code from ketlul--pandya and edit the knock function by adding knock-knock api

**Comment by KavanGandhi** [comment]
Means tya jokes vadu j add karvani che api?

**Comment by KavanGandhi** [comment]
K knock vadu alag che?

**Comment by 13Aluminium** [comment]
No your first comment is the correct one you have to add a knock knock api there the coding part is done(take the code from ketul-pandya) you just have to push it to you own branch

**Comment by 13Aluminium** [comment]
Thanks @KavanGandhi for resolving this issue.
