### ISSUE TITLE
Home page terminal image is superimposing the content

### ISSUE THREAD

**Issue by 13Aluminium** [13Aluminium/term#91]
![homepag1](https://user-images.githubusercontent.com/110249518/225665238-0056eb7b-725a-4f34-90c4-65513ac1613f.png)

![homepage2](https://user-images.githubusercontent.com/110249518/225665297-9138f7d6-f172-45ea-a051-392e43dae314.png)
@YashKhandelwal-tc
as shown in above images there is superimposition of terminal image.

**Comment by yashkhandelwal123** [comment]
I will resolve it.
please assign it to me.

**Comment by 13Aluminium** [comment]
Thanks for resolving this issue with such speed and accuracy @yashkhandelwal123
